const items = [
    'Maybe.',
    'Certainly not.',
    'I hope so.',
    'Not in your wildest dreams.',
    'There is a good chance.',
    'In your dreams.',
    'Quite likely.',
    'I think so.',
    'I hope not.',
    'I hope so.',
    'Never!',
    'Pfft.',
    'Sorry, bucko.',
    'Hell, yes.',
    'Hell to the no.',
    'The future is bleak.',
    'The future is uncertain.',
    'I would rather not say.',
    'Who cares?',
    'Possibly.',
    'Never, ever, ever.',
    'There is a small chance.',
    'As I see it, yes',
    'It is certain',
    'It is decidedly so',
    'Most likely',
    'Outlook good',
    'Signs point to yes',
    'Yes!',
    'Couldn\'t care less.',
    'Fuck that.'
  ]

  module.exports = {items}